FROM python:3.9

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get -y install git python3-pip python3-distutils python3-dev tzdata locales locales-all fonts-wqy-microhei fonts-wqy-zenhei fontconfig libxt6 libxrender1 \
    libjpeg-dev libpng-dev libtiff-dev libwebp-dev libopenjp2-7-dev libfreetype6-dev liblcms2-dev libmagickwand-dev libx11-dev fonts-courier-prime \
    build-essential python3-dev python3-pip python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info && \
    locale-gen de_DE.UTF-8 &&\
    echo "Europe/Berlin" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata

ENV LANG "de_DE.UTF-8"
ENV LANGUAGE "de_DE.UTF-8"
ENV LC_ALL "de_DE.UTF-8"
ENV TZ "Europe/Berlin"

# INSTALL REQUIREMENTS
WORKDIR /tmp
COPY /server/requirements.txt /tmp/requirements.txt
RUN pip install -r requirements.txt
