name: Docker Image CI

on:
  push:
    branches:
      - master
      - main
      - stable
    paths:
      - 'Dockerfile'
      - 'Dockerfile_base'
      - 'build.sh'
      - 'build_stack.sh'
      - 'server/COMMIT_HASH'
  pull_request:
    branches:
      - master
      - main
    paths:
      - 'Dockerfile'
      - 'Dockerfile_base'
      - 'build.sh'
      - 'build_stack.sh'
      - 'server/COMMIT_HASH'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build the Docker image
        run: ./build_stack.sh