name: Docker Image CI

on:
  push:
    branches:
      - master
      - main
      - stable
    paths:
      - 'Dockerfile'
      - 'server/COMMIT_HASH'
  pull_request:
    branches:
      - master
      - main
    paths:
      - 'Dockerfile'
      - 'server/COMMIT_HASH'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build the Docker image
      run: |
          COMMIT_HASH=$(<server/COMMIT_HASH)
          IMAGE_NAME="ghcr.io/${{ github.repository }}"

          # Build image for master branch
          if [ ${{ github.ref }} == 'refs/heads/master' ] || [ ${{ github.ref }} == 'refs/heads/main' ]; then
            CHANNEL="latest"
          fi

          # Build image for stable branch
          if [ ${{ github.ref }} == 'refs/heads/stable' ]; then
            CHANNEL="stable"
          fi

          docker build . --file Dockerfile --tag ${IMAGE_NAME}:${COMMIT_HASH}
          docker push ${IMAGE_NAME}:${COMMIT_HASH}

          docker build . --file Dockerfile --tag ${IMAGE_NAME}:${CHANNEL}
          docker push ${IMAGE_NAME}:${CHANNEL}