name: mkdocs 
on:
  push:
    branches:
      - master 
      - main
    paths:
      - 'docs/**'
      - 'examples/**'
      - 'docker-compose.yml'
      - 'mkdocs.yml'
      - '.github/workflows/mkdocs.yml'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: |
          echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
          echo "build_doc_date=$(date -u '+%d.%m.%Y')" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(<server/COMMIT_HASH)" >> $GITHUB_ENV
          echo "COMMIT_DATE=$(<server/COMMIT_DATE)" >> $GITHUB_ENV
          echo "change_date_ds=$(git log -1 --format=%cd --date=format:'%d.%m.%Y' -- docs/datenschutz.md)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdocs-macros-plugin mkdocs-glightbox
      - run: mkdocs gh-deploy --force
